name: deploy on ec2
on :
  push:
    branches: [master]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout source
        uses: actions/checkout@v3
      - name: login to docker hub
        run: docker login -u ${{ secrets.dockerUser }} -p ${{ secrets.dockerPass }}
      - name: build docker image
        run: docker build -t node-todo .
      - name: changing the name of image 
        run: docker tag node-todo ${{ secrets.dockerUser }}/node-todo:latest
      - name: push the image to docker
        run: docker push ${{ secrets.dockerUser }}/node-todo:latest
      - name: run the container
        run: docker-compose down && docker-compose up -d
